# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    unit.controller.admin:
        class: WellCommerce\Bundle\UnitBundle\Controller\Admin\UnitController
        arguments: ['@unit.manager', '@unit.form_builder.admin', '@unit.datagrid']
        calls:
            - [setContainer, ['@service_container']]
