WellCommerce\Bundle\UnitBundle\Entity\Unit:
    fields:
        id:
            groups:
                - default
                - unit
    associations:
        translations:
            groups:
                - unit
